### ISSUE TITLE
Changing FFmpeg version should invalidate ContentLength cache

### ISSUE THREAD

**Issue by chvp** [accentor/api#175]
- [x] There are no similar issues reported yet

**Describe the bug**
Changes to the FFmpeg internals can change the encoded length of files, breaking clients depending on this length being correct (like the android app).

**To Reproduce**
Find two ffmpeg version that encode to different sizes with the same settings.

**Expected behavior**
The way to fix this is probably to parse out the FFmpeg version on startup. If we add an `ffmpeg_version` field to the ContentLength cache we can delete the entries that don't have a matching version.

Open question: Do we want to queue jobs for ContentLength creation for the AudioFile/CodecConversion combinations that don't have a matching ContentLength? This probably improves user experience, but queuing `|codec_conversion| * |audio_file|` conversion jobs isn't something we want to do on the regular 😬.

**Comment by charvp** [comment]
Instead of recalculating for all audio files we could also filter on length. For tracks of an hour the conversion delay is annoying, where for 3 minute tracks it isn't noticeable.

**Comment by robbevp** [comment]
Don’t think we need this on every track in advance for all CodecConversions. There's a good chance that most of these ContentLengths would never get used.

I would maybe queue a new calculation for all ContentLength that were destroyed? Those have a higher chance of being used again.

**Comment by charvp** [comment]
Right now the application tries to guarantee a ContentLength existing for every AudioFile/CodecConversion combination by queuing calculations on CodecConversion create and AudioFile create. If you queue an hour-long track in the app it takes a good minute to start playing if the ContentLength doesn't exist, which is definitely not a good experience.

**Comment by robbevp** [comment]
Then we already queue this for every combination, no? Or am I missing something?

If FFmpeg has frequent updates, I would avoid recreating them everytime so, but that doesn't really seem to be the case (based on their "news" section)

**Comment by charvp** [comment]
Yes, we queue them for every combination. ContentLengths are never deleted right now (except for manual action), so new creations only trickle in with rescans (since new CodecConversions are very rare). If we decide to recreate them all on ffmpeg version bumps, it would mean a lot of CPU cycles for users at once.

**Comment by robbevp** [comment]
Think this will be a question of balance demand vs the load required.

We can never fully predixt demand but one option would be to
* always do tracks over a certain length
* always do tracks that were created in the last month or two (since those have a higher chance of being requested)
* use plays to predict which tracks are more likely to be requested (those played in the last X time, or not those which have never been played, ...)
